# Generated by Django 6.0a1 on 2025-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название локации')),
                ('place_id', models.CharField(max_length=100, unique=True, verbose_name='ID локации')),
                ('details_url', models.URLField(verbose_name='URL для сведений (JSON)')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['title'],
            },
        ),
    ]
