# Generated by Django 6.0a1 on 2025-10-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='details_url',
        ),
        migrations.AddField(
            model_name='location',
            name='description_long',
            field=models.TextField(blank=True, verbose_name='Длинное описание'),
        ),
        migrations.AddField(
            model_name='location',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=55.75, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='locations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.location')),
            ],
            options={
                'verbose_name': 'Фото локации',
                'verbose_name_plural': 'Фото локаций',
            },
        ),
    ]
